### ISSUE TITLE
Nested brackets

### ISSUE THREAD

**Issue by Gavin-Holt** [deusnefum/micro-bounce#2]
Hi

If I have nested brackets then repeated use of bounce leads to the smallest possible selection e.g.:

    shell.RunCommand([[MSGBOX.EXE ]]..[["]]..text..[[" "]]..title..[["]]) 

Starting from the first (, will always end with jumps either side of the last double quote. 

I see from the code that the first time bounce is called it does not store the type of bracket found.

Would you consider storing the bracket type to ensure a "bounce back"?

Kind Regards Gavin Holt

**Comment by sparques** [comment]
This plugin uses micro's internal MatchBrace function and this is how it works. If you want to change how match brace works, please file an issue against micro editor itself.

https://github.com/zyedidia/micro/blob/de8f4bf72f20313326f7b2666efadf49bf1a433b/internal/buffer/buffer.go#L929

(I agree this behavior is annoying / overly quirky)

**Comment by sparques** [comment]
Been a while since I looked at this. Looks like one of the things returned is a "on the left" indicator which I should be able to use to fix this. I'll see if I can't fix it, otherwise I'll file an issue with micro-editor.

**Comment by Gavin-Holt** [comment]
Thanks

**Comment by sparques** [comment]
@Gavin-Holt, release 1.1.2 fixes this! You can update with `plugin update bounce`; or if that gives you gruff like it did for me, do `plugin remove bounce` and then `plugin install bounce`

**Comment by Gavin-Holt** [comment]
Thanks works like a charm.

Kind Regards Gavin Holt
