### ISSUE TITLE
Shift-Bounce

### ISSUE THREAD

**Issue by Gavin-Holt** [deusnefum/micro-bounce#3]
Hi

I am having difficulty discovering the Lua methods/functions for micro. I would like a second bounce function which selects text inside the detected brackets. I guess I need to extend the selection in the "if ok" section?

All help gratefully received.

Kind Regards Gavin Holt

**Comment by sparques** [comment]
Perhaps looking at micro-quoter would help? https://github.com/deusnefum/micro-quoter/blob/master/quoter.lua

This functionality would fit better in that plugin too.

**Comment by Gavin-Holt** [comment]
Hi

May thanks  - I think I can work it out from your example.

Kind Regards Gavin
